# Generated by Django 5.2.7 on 2025-11-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('create_list_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد لیست')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
            ],
            options={
                'verbose_name': 'ToDoList',
                'verbose_name_plural': 'ToDoLists',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایین')),
                ('public', models.BooleanField(default=False, help_text='اگر شما این گزینه را انتخاب کنید بقیه به این کار دسترسی دارند', verbose_name='عمومی')),
                ('for_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار ها',
            },
        ),
    ]
