# Generated by Django 5.2.7 on 2025-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bale_id',
            field=models.CharField(max_length=110, null=True, verbose_name='شناسه بله'),
        ),
    ]
